apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-spew
spec:
  selector:
    matchLabels:
      app: go-spew
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-spew
        logstream: go-spew
      annotations:
        logging.parser: json
        fluentbit.io/parser: json
        logging.topic: k8s-watermark
    spec:
      containers:
      - name: go-spew
        image: stevenacoffman/go_spew@sha256:af0889dfbba33820196083c4a4da18df02d4b9cf6015a187f75161e824694a8b
        env:
        - name: APP_NAME
          value: go-spew
        - name: INTERVAL
          value: "30"
        - name: DEBUG
          value: "false"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
