version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: "${GIT_COMMIT}"
        GIT_BRANCH: "${GIT_BRANCH}"
        BUILD_TIME: "${BUILD_TIME}"
    image: stevenacoffman/go_spew
    volumes:
      - ~/Downloads:/var/run/secrets/kubernetes.io/serviceaccount
    environment:
      - APP_NAME=go-spew
    tty: true
volumes:
    notused:
